### ISSUE TITLE
Spag request list panics with a relative requests directory

### ISSUE THREAD

**Issue by pglass** [pglbutt/noodles#68]
$ spag env set dir tests/resources/
    $ spag request list
    thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:362

**Comment by Squab** [comment]
Samesies here.
```
$ spag env set dir tests/templates/
---
"dir": "tests/templates/"
$ spag request list
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:362
```
